# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20151212_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_event',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('sp', 'Sport'), ('ed', 'Educativ'), ('mu', 'Muzical'), ('fo', 'Gastronomie'), ('pa', 'Party'), ('re', 'Religios'), ('fi', 'Film'), ('ba', 'Bautura')], max_length=2),
        ),
    ]
