# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20151213_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('ba', 'Bautura'), ('pa', 'Party'), ('re', 'Religios'), ('fi', 'Film'), ('fo', 'Gastronomie'), ('ed', 'Educativ'), ('mu', 'Muzical'), ('sp', 'Sport')], max_length=2),
        ),
    ]
